# Generated by Django 5.2.5 on 2026-01-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
