# Generated by Django 5.2.5 on 2026-01-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapi", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="checkout_request_id",
            field=models.CharField(
                blank=True,
                help_text="CheckoutRequestID from M-Pesa STK Push",
                max_length=100,
                null=True,
                verbose_name="M-Pesa checkout request ID",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="payment received"),
        ),
        migrations.AddField(
            model_name="order",
            name="mpesa_receipt_number",
            field=models.CharField(
                blank=True,
                help_text="M-Pesa transaction receipt from callback",
                max_length=100,
                null=True,
                verbose_name="M-Pesa receipt number",
            ),
        ),
    ]
