# Generated by Django 5.2.5 on 2026-01-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapi", "0003_order_checkout_request_id_order_is_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when payment was confirmed via M-Pesa callback",
                null=True,
                verbose_name="payment confirmed at",
            ),
        ),
    ]
